### ISSUE TITLE
Update to latest libmseed master to produce approved Source Identifiers in mseed3

### ISSUE THREAD

**Issue by chad-earthscope** [andres-h/seedlink4#1]
Current identifiers for miniSEED 3 packets contain an `XFDSN` prefix, whereas in the final approved specification the prefix is now simply `FDSN`.  I assume these are created by libmseed, which has been updated to produce the approved Source Identifiers:

https://github.com/iris-edu/libmseed

I would prefer to eradicate this anomaly of checking for `FDSN` and `XFDSN` as soon as possible.

**Comment by andres-h** [comment]
libmseed upgraded to 3.0.9
